language: scala

before_script:
  - sudo chmod +x /usr/local/bin/sbt

# only trigger builds on master
branches:
  only:
    - master

script:
  - sbt clean coverage test coverageReport

before_install:
    - pip install --user codecov

after_success:
  - codecov

jdk:
  - oraclejdk8
